### ISSUE TITLE
Cambiare google maps

### ISSUE THREAD

**Issue by annapiera** [socrates-it/socrates-it.github.io#12]
Cambiare mappa con codice sotto

`<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11466.733896069858!2d12.5799073!3d44.0692443!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xa0d37c9d07777d6b!2sHotel%20Sporting%20Rimini!5e0!3m2!1sit!2sch!4v1651576933196!5m2!1sit!2sch" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
`

**Comment by arialdomartini** [comment]
Done!
