### ISSUE TITLE
Change "location" text

### ISSUE THREAD

**Issue by annapiera** [socrates-it/socrates-it.github.io#13]
Location
We are going to be in the hotel, night and day. That is why we have chosen the [Hotel Sporting Rimini](https://www.hotelsportingrimini.com/) in Rimini (RN) as our location for the unconference.

Since one of the important aspects of SoCraTes is being close to the “action”, everything will happen within the location: lodging, eating and mingling. As a result, we can only accept as many participants as the number of available rooms!

**Comment by arialdomartini** [comment]
Fatto.
Sulla parola Rimini ho aggiunto un link al Google Maps dell'Hotel.
