### ISSUE TITLE
Cambiare colori menu

### ISSUE THREAD

**Issue by annapiera** [socrates-it/socrates-it.github.io#14]
![image](https://user-images.githubusercontent.com/47472672/166490136-bb7c4639-688a-4dee-be33-7709fb1dbfee.png)
Vorrei snellire un po' il menu.

Sfondo: da nero a bianco
Scritte: da bianche a nere

Vediamo come si comportano i bottoni e il logo

**Comment by arialdomartini** [comment]
Appare così

![image](https://user-images.githubusercontent.com/150719/170856639-5aa0108d-3898-429e-8633-41b8251c6a7a.png)


Dimmi pure se procedere @annapiera!

**Comment by annapiera** [comment]
Mi piace!! :) Procedi @arialdomartini

**Comment by arialdomartini** [comment]
OK.
Conta che con l'immagine di sfondo viene in questo modo

![image](https://user-images.githubusercontent.com/150719/172071475-025db447-d33c-4cec-afc9-fdb8290d99e7.png)


Se dovessi cambiare idea, posso usare facilmente un altro colore, anche molto chiaro, tipo

![image](https://user-images.githubusercontent.com/150719/172071537-7ff3af10-204d-47b0-a165-916c21993042.png)

**Comment by arialdomartini** [comment]
Atrimenti un bordino come questo?
![image](https://user-images.githubusercontent.com/150719/172072236-fd76c658-9b36-400e-ae6f-14ddf1bc34da.png)
