### ISSUE TITLE
What is included in the cost? / change

### ISSUE THREAD

**Issue by annapiera** [socrates-it/socrates-it.github.io#16]
**What is included in the cost?**

- Two nights full-board: breakfast, lunch, dinner and snack buffet all day (vegetarian and gluten-free food included!)
- Use of the congress rooms
- The hotel has both twin and double rooms. If there is someone you are willing to share the room with, feel free to book the double room. If you don’t know anyone, don’t worry: sign in to the [Sofware Crafters #italian channel on Slack](http://bit.ly/SlackSocrates) and find a suitable roommate.
- City tax

**Why is the cost variable?**

SoCraTes IT is a no-profit event, which implies that the exact cost of a ticket will depend on the amount of sponsorship we receive. All the sponsorship money will cover the cost of the congress rooms. It could be also used to offer extra amenities during the conference or to reduce the ticket prices for all participants.

**Comment by arialdomartini** [comment]
Done.
@annapiera  Cosa devo fare con la frase

The unconference’s beverages will be covered by the sponsors.

**Comment by arialdomartini** [comment]
@annapiera per adesso **non** l'ho inclusa.

**Comment by annapiera** [comment]
Ciao Ari, il testo è quello di sopra, pari pari.
Non abbiamo parlato di costi per le bevande coperti dagli sponsor per ora. :) 
@arialdomartini

**Comment by annapiera** [comment]
Qui: Sofware Crafters #italian channel on Slack
ci siamo persi l'hyperlink: http://slack.softwarecraftsmanship.org/

**Comment by arialdomartini** [comment]
Ok, aggiunto il link
