### ISSUE TITLE
Cambiare mappa google

### ISSUE THREAD

**Issue by annapiera** [socrates-it/socrates-it.github.io#18]
Mappa dell'hotel ambasciatori: 

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2866.7033423208427!2d12.577975515511294!3d44.06883407910921!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132cc377163d5c69%3A0x342e6d3ad7ed633a!2sHotel%20Ambasciatori%20Rimini!5e0!3m2!1sit!2sch!4v1654065074501!5m2!1sit!2sch" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

**Comment by annapiera** [comment]
Please, note - la mappa la facciamo rettangolare, lunga quanto la pagina. ;)

**Comment by arialdomartini** [comment]
Done
