### ISSUE TITLE
Location: change text

### ISSUE THREAD

**Issue by annapiera** [socrates-it/socrates-it.github.io#19]
We are going to be together in the hotel, night and day. That is why we have chosen the [Hotel Ambasciatori ****](https://www.hotelambasciatori.it/) in Rimini (RN) as our main location for the unconference.

We will move to the near restaurant to enjoy our lunch and dinner. 

Since one of the important aspects of SoCraTes is being close to the “action", we could only accept as many participants as the number of available rooms!

**Comment by arialdomartini** [comment]
Done. Ho messo anche un link a maps.
