### ISSUE TITLE
Rooms: change text

### ISSUE THREAD

**Issue by annapiera** [socrates-it/socrates-it.github.io#20]
Double room: 226€ per attendee
Single room: 286€ per attendee

**Comment by arialdomartini** [comment]
Cambiato.
Ho tolto il paragrafo:


## Why is the cost variable?

SoCraTes IT is a no-profit event, which implies that the exact cost of a ticket will depend on the amount of sponsorship we receive. All the sponsorship money will cover the cost of the congress rooms. It could be also used to offer extra amenities during the conference or to reduce the ticket prices for all participants.
