### ISSUE TITLE
Cambiare header homepage

### ISSUE THREAD

**Issue by annapiera** [socrates-it/socrates-it.github.io#8]
Spostiamo l'immagine a destra, inserire quella in allegato.

**Comment by annapiera** [comment]
[business-people-planning-working-with-task-board.zip](https://github.com/socrates-it/socrates-it.github.io/files/8611852/business-people-planning-working-with-task-board.zip)

**Comment by arialdomartini** [comment]
Hey, @annapiera, intedi così?

![image](https://user-images.githubusercontent.com/150719/169639586-51944180-48fd-43ca-b0ba-7662d7bea0b0.png)


Non ho capito cosa tu intenda con spostare l'immagine a destra...

**Comment by annapiera** [comment]
Mhhh. Brutttina.

Prova a mettere questa: https://www.freepik.com/free-vector/hand-drawn-flat-design-gathering-data-business-concept_19822330.htm#page=2&query=developer&position=21&from_view=search
Però mettendoci su un velo opaco, come nell'header di prima.

Pleaaase <3

**Comment by arialdomartini** [comment]
Penso che questa vada da coordinare con #14, giusto? Sentiamoci a voce.

**Comment by annapiera** [comment]
@arialdomartini  non riusciamo solo a cambiare l'header? 
Sentiamoci se vuoi!

**Comment by arialdomartini** [comment]
Fatto!
