### ISSUE TITLE
Cambiare testo header homepage

### ISSUE THREAD

**Issue by annapiera** [socrates-it/socrates-it.github.io#9]
4-6 June 2020 -> 22-24 September 2022

Dimaro (Trento) -> Rimini

**Comment by annapiera** [comment]
Spostiamo il testo a sinistra su sfondo bianco.
Effetto come immagine sotto.

![image](https://user-images.githubusercontent.com/47472672/166491240-6895baca-9624-46d2-bdfc-c4aae0c05e4b.png)

**Comment by arialdomartini** [comment]
@annapiera Ho cambiato la data.
Non ho capito il secondo commento. A quale pagina si riferisce?

**Comment by annapiera** [comment]
Il secondo commento era per la foto dell'header. :'D Lascia stare, cambiamo foto! @arialdomartini
